import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const adminClient = createClient(supabaseUrl, serviceRoleKey, {
  auth: { autoRefreshToken: false, persistSession: false },
})

const books = [
  // === Self Improvement ===
  {
    judul: 'Atomic Habits: Perubahan Kecil yang Memberikan Hasil Luar Biasa',
    penulis: 'James Clear',
    penerbit: 'Gramedia Pustaka Utama',
    tahun: 2019,
    kategori: 'Self Improvement',
    isbn: '9786020633176',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Membahas bagaimana kebiasaan kecil yang dilakukan secara konsisten dapat menghasilkan perubahan besar dalam kehidupan.',
  },
  {
    judul: 'The Psychology of Money',
    penulis: 'Morgan Housel',
    penerbit: 'Harriman House',
    tahun: 2020,
    kategori: 'Self Improvement',
    isbn: '9780857197689',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Menjelaskan bahwa keberhasilan finansial lebih dipengaruhi oleh perilaku daripada kecerdasan.',
  },
  {
    judul: 'The Mountain Is You',
    penulis: 'Brianna Wiest',
    penerbit: 'Thought Catalog Books',
    tahun: 2020,
    kategori: 'Self Improvement',
    isbn: '9781949759228',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Membahas cara mengatasi sabotase diri dan mengembangkan potensi pribadi.',
  },
  {
    judul: 'Ikigai',
    penulis: 'Héctor García & Francesc Miralles',
    penerbit: 'Penguin Books',
    tahun: 2017,
    kategori: 'Self Improvement',
    isbn: '9780143130727',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Mengulas filosofi hidup masyarakat Jepang dalam menemukan tujuan hidup.',
  },
  {
    judul: "The Subtle Art of Not Giving a F*ck",
    penulis: 'Mark Manson',
    penerbit: 'HarperOne',
    tahun: 2016,
    kategori: 'Self Improvement',
    isbn: '9780062457714',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Mengajarkan pentingnya memilih hal-hal yang benar-benar layak untuk dipedulikan.',
  },
  // === Romance ===
  {
    judul: 'Better Than the Movies',
    penulis: 'Lynn Painter',
    penerbit: 'Simon & Schuster',
    tahun: 2021,
    kategori: 'Romance',
    isbn: '9781534467637',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Kisah cinta remaja yang dipenuhi momen lucu dan mengharukan.',
  },
  {
    judul: 'Book Lovers',
    penulis: 'Emily Henry',
    penerbit: 'Berkley',
    tahun: 2022,
    kategori: 'Romance',
    isbn: '9780593334836',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Dua pekerja industri buku menemukan cinta saat liburan.',
  },
  {
    judul: 'Happy Place',
    penulis: 'Emily Henry',
    penerbit: 'Berkley',
    tahun: 2023,
    kategori: 'Romance',
    isbn: '9780593441275',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Mantan pasangan berpura-pura masih bersama demi menjaga suasana liburan bersama teman.',
  },
  {
    judul: 'Every Summer After',
    penulis: 'Carley Fortune',
    penerbit: 'Berkley',
    tahun: 2022,
    kategori: 'Romance',
    isbn: '9780593438534',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Cinta pertama yang kembali hadir setelah bertahun-tahun berpisah.',
  },
  {
    judul: 'Love, Theoretically',
    penulis: 'Ali Hazelwood',
    penerbit: 'Berkley',
    tahun: 2023,
    kategori: 'Romance',
    isbn: '9780593638859',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Kisah cinta yang berlatar dunia akademik dan sains.',
  },
  // === Fantasy ===
  {
    judul: 'Fourth Wing',
    penulis: 'Rebecca Yarros',
    penerbit: 'Red Tower Books',
    tahun: 2023,
    kategori: 'Fantasy',
    isbn: '9781649374042',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Seorang gadis mengikuti akademi penunggang naga yang penuh bahaya.',
  },
  {
    judul: 'Iron Flame',
    penulis: 'Rebecca Yarros',
    penerbit: 'Red Tower Books',
    tahun: 2023,
    kategori: 'Fantasy',
    isbn: '9781649374172',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Kelanjutan perjuangan Violet menghadapi perang dan rahasia besar.',
  },
  {
    judul: 'A Court of Thorns and Roses',
    penulis: 'Sarah J. Maas',
    penerbit: 'Bloomsbury',
    tahun: 2015,
    kategori: 'Fantasy',
    isbn: '9781635575569',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Kisah manusia yang memasuki dunia peri penuh intrik.',
  },
  {
    judul: 'Throne of Glass',
    penulis: 'Sarah J. Maas',
    penerbit: 'Bloomsbury',
    tahun: 2012,
    kategori: 'Fantasy',
    isbn: '9781619630345',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Seorang pembunuh bayaran bertarung demi kebebasannya.',
  },
  {
    judul: 'Babel',
    penulis: 'R.F. Kuang',
    penerbit: 'Harper Voyager',
    tahun: 2022,
    kategori: 'Fantasy',
    isbn: '9780063021426',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Fantasi gelap mengenai kolonialisme dan kekuatan bahasa.',
  },
  // === Thriller & Mystery ===
  {
    judul: 'The Housemaid',
    penulis: 'Freida McFadden',
    penerbit: 'Bookouture',
    tahun: 2022,
    kategori: 'Thriller & Mystery',
    isbn: '9781803144382',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Seorang pembantu rumah tangga menemukan rahasia kelam majikannya.',
  },
  {
    judul: 'None of This Is True',
    penulis: 'Lisa Jewell',
    penerbit: 'Atria Books',
    tahun: 2023,
    kategori: 'Thriller & Mystery',
    isbn: '9781982179007',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Podcast mengungkap misteri kehidupan seorang wanita.',
  },
  {
    judul: 'The Silent Patient',
    penulis: 'Alex Michaelides',
    penerbit: 'Celadon Books',
    tahun: 2019,
    kategori: 'Thriller & Mystery',
    isbn: '9781250301697',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Psikolog mencoba mengungkap alasan seorang wanita berhenti berbicara setelah membunuh suaminya.',
  },
  {
    judul: 'The Maid',
    penulis: 'Nita Prose',
    penerbit: 'Ballantine Books',
    tahun: 2022,
    kategori: 'Thriller & Mystery',
    isbn: '9780593356159',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Petugas kebersihan hotel menjadi tersangka pembunuhan.',
  },
  {
    judul: 'The Paris Apartment',
    penulis: 'Lucy Foley',
    penerbit: 'HarperCollins',
    tahun: 2022,
    kategori: 'Thriller & Mystery',
    isbn: '9780008514181',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Hilangnya seorang pria membuka berbagai rahasia penghuni apartemen.',
  },
  // === Young Adult (YA) ===
  {
    judul: 'The Inheritance Games',
    penulis: 'Jennifer Lynn Barnes',
    penerbit: 'Little Brown',
    tahun: 2020,
    kategori: 'Young Adult (YA)',
    isbn: '9781368052405',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'One of Us Is Lying',
    penulis: 'Karen M. McManus',
    penerbit: 'Delacorte Press',
    tahun: 2017,
    kategori: 'Young Adult (YA)',
    isbn: '9781524714680',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'We Were Liars',
    penulis: 'E. Lockhart',
    penerbit: 'Delacorte Press',
    tahun: 2014,
    kategori: 'Young Adult (YA)',
    isbn: '9780385741262',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Divine Rivals',
    penulis: 'Rebecca Ross',
    penerbit: 'Wednesday Books',
    tahun: 2023,
    kategori: 'Young Adult (YA)',
    isbn: '9781250857439',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'If He Had Been with Me',
    penulis: 'Laura Nowlin',
    penerbit: 'Sourcebooks Fire',
    tahun: 2013,
    kategori: 'Young Adult (YA)',
    isbn: '9781402277825',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  // === Business & Finance ===
  {
    judul: 'Rich Dad Poor Dad',
    penulis: 'Robert T. Kiyosaki',
    penerbit: 'Plata Publishing',
    tahun: 1997,
    kategori: 'Business & Finance',
    isbn: '9781612681139',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'The Intelligent Investor',
    penulis: 'Benjamin Graham',
    penerbit: 'Harper Business',
    tahun: 2006,
    kategori: 'Business & Finance',
    isbn: '9780060555665',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'The Lean Startup',
    penulis: 'Eric Ries',
    penerbit: 'Crown Business',
    tahun: 2011,
    kategori: 'Business & Finance',
    isbn: '9780307887894',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Zero to One',
    penulis: 'Peter Thiel',
    penerbit: 'Crown Business',
    tahun: 2014,
    kategori: 'Business & Finance',
    isbn: '9780804139298',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Psychology of Money',
    penulis: 'Morgan Housel',
    penerbit: 'Harriman House',
    tahun: 2020,
    kategori: 'Business & Finance',
    isbn: '9780857197689-2',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  // === Technology & Artificial Intelligence ===
  {
    judul: 'Co-Intelligence',
    penulis: 'Ethan Mollick',
    penerbit: 'Portfolio',
    tahun: 2024,
    kategori: 'Technology & Artificial Intelligence',
    isbn: '9780593716717',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'AI Engineering',
    penulis: 'Chip Huyen',
    penerbit: "O'Reilly Media",
    tahun: 2025,
    kategori: 'Technology & Artificial Intelligence',
    isbn: '9781098166304',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Life 3.0',
    penulis: 'Max Tegmark',
    penerbit: 'Knopf',
    tahun: 2017,
    kategori: 'Technology & Artificial Intelligence',
    isbn: '9781101946596',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'The Alignment Problem',
    penulis: 'Brian Christian',
    penerbit: 'W.W. Norton',
    tahun: 2020,
    kategori: 'Technology & Artificial Intelligence',
    isbn: '9780393635829',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Human Compatible',
    penulis: 'Stuart Russell',
    penerbit: 'Viking',
    tahun: 2019,
    kategori: 'Technology & Artificial Intelligence',
    isbn: '9780525558613',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  // === Psychology ===
  {
    judul: 'Thinking, Fast and Slow',
    penulis: 'Daniel Kahneman',
    penerbit: 'Farrar, Straus and Giroux',
    tahun: 2011,
    kategori: 'Psychology',
    isbn: '9780374533557',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Surrounded by Idiots',
    penulis: 'Thomas Erikson',
    penerbit: "St. Martin's Press",
    tahun: 2019,
    kategori: 'Psychology',
    isbn: '9781250179944',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'The Body Keeps the Score',
    penulis: 'Bessel van der Kolk',
    penerbit: 'Penguin',
    tahun: 2014,
    kategori: 'Psychology',
    isbn: '9780143127741',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Emotional Intelligence',
    penulis: 'Daniel Goleman',
    penerbit: 'Bantam Books',
    tahun: 1995,
    kategori: 'Psychology',
    isbn: '9780553383713',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Attached',
    penulis: 'Amir Levine & Rachel Heller',
    penerbit: 'TarcherPerigee',
    tahun: 2010,
    kategori: 'Psychology',
    isbn: '9781585429134',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  // === Productivity ===
  {
    judul: 'Deep Work',
    penulis: 'Cal Newport',
    penerbit: 'Grand Central Publishing',
    tahun: 2016,
    kategori: 'Productivity',
    isbn: '9781455586691',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Essentialism',
    penulis: 'Greg McKeown',
    penerbit: 'Crown Business',
    tahun: 2014,
    kategori: 'Productivity',
    isbn: '9780804137386',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Getting Things Done',
    penulis: 'David Allen',
    penerbit: 'Penguin Books',
    tahun: 2015,
    kategori: 'Productivity',
    isbn: '9780143126560',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Eat That Frog!',
    penulis: 'Brian Tracy',
    penerbit: 'Berrett-Koehler',
    tahun: 2017,
    kategori: 'Productivity',
    isbn: '9781626569416',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  {
    judul: 'Make Time',
    penulis: 'Jake Knapp & John Zeratsky',
    penerbit: 'Currency',
    tahun: 2018,
    kategori: 'Productivity',
    isbn: '9780525572428',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Tidak ada sinopsis',
  },
  // === Science Fiction (Sci-Fi) ===
  {
    judul: 'Dune',
    penulis: 'Frank Herbert',
    penerbit: 'Ace Books',
    tahun: 1965,
    kategori: 'Science Fiction (Sci-Fi)',
    isbn: '9780441172719',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Perebutan kekuasaan di planet Arrakis yang menjadi sumber rempah paling berharga di galaksi.',
  },
  {
    judul: 'Project Hail Mary',
    penulis: 'Andy Weir',
    penerbit: 'Ballantine Books',
    tahun: 2021,
    kategori: 'Science Fiction (Sci-Fi)',
    isbn: '9780593135204',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Seorang ilmuwan terbangun sendirian di luar angkasa untuk menyelamatkan umat manusia.',
  },
  {
    judul: 'The Three-Body Problem',
    penulis: 'Liu Cixin',
    penerbit: 'Tor Books',
    tahun: 2014,
    kategori: 'Science Fiction (Sci-Fi)',
    isbn: '9780765377067',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Kontak pertama manusia dengan peradaban alien memicu konflik besar.',
  },
  {
    judul: 'Dark Matter',
    penulis: 'Blake Crouch',
    penerbit: 'Crown Publishing',
    tahun: 2016,
    kategori: 'Science Fiction (Sci-Fi)',
    isbn: '9781101904220',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Seorang fisikawan terjebak di dunia paralel dan berusaha kembali ke keluarganya.',
  },
  {
    judul: 'Ready Player One',
    penulis: 'Ernest Cline',
    penerbit: 'Crown Publishing',
    tahun: 2011,
    kategori: 'Science Fiction (Sci-Fi)',
    isbn: '9780307887443',
    cetakan: 'Ke-1',
    stok: 5,
    cover: null,
    preview: null,
    sinopsis: 'Remaja mengikuti perburuan harta karun di dunia virtual yang menentukan masa depan umat manusia.',
  },
]

async function seed() {
  console.log(`Seeding ${books.length} books...`)

  const { data, error } = await adminClient.from('buku').insert(books).select()

  if (error) {
    console.error('Error seeding books:', error.message)
    process.exit(1)
  }

  console.log(`Successfully seeded ${data.length} books!`)
  process.exit(0)
}

seed()
